export const GET_CARS_LOAD = "GET_CARS_LOAD";
export const GET_CARS_SUCCESS = "GET_CARS_SUCCESS";
export const GET_CARS_FAIL = "GET_CARS_FAIL";

export const GET_CAR_BYID_LOAD = "GET_CAR_BYID_LOAD";
export const GET_CAR_BYID_SUCCESS = "GET_CAR_BYID_SUCCESS";
export const GET_CAR_BYID_FAIL = "GET_CAR_BYID_FAIL";

export const DELETE_CAR_BYID_LOAD = "DELETE_CAR_BYID_LOAD";
export const DELETE_CAR_BYID_SUCCESS = "DELETE_CAR_BYID_SUCCESS";
export const DELETE_CAR_BYID_FAIL = "DELETE_CAR_BYID_FAIL";

export const ADD_CAR_LOAD = "ADD_CAR_LOAD";
export const ADD_CAR_SUCCESS = "ADD_CAR_SUCCESS";
export const ADD_CAR_FAIL = "ADD_CAR_FAIL";

export const EDIT_CAR_LOAD = "EDIT_CAR_LOAD";
export const EDIT_CAR_SUCCESS = "EDIT_CAR_SUCCESS";
export const EDIT_CAR_FAIL = "EDIT_CAR_FAIL";